obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX8) += goodix_gtx8_touch.o

goodix_gtx8_touch-y	:= goodix_ts_i2c.o  \
		goodix_ts_core.o \
		goodix_cfg_bin.o  \
		goodix_gtx8_update.o \
		goodix_ts_gesture.o \
		goodix_ts_tools.o \
		goodix_ts_test.o
